## Common Values
namespace: mediator


## Deployment Values
deployment_name: mediator
replicas: 1

image: 
  name: ghcr.io/openwallet-foundation/didcomm-mediator-credo
  tag: latest

container:
  name: mediator
  port: 3000

environment:
  AGENT_PORT: 3000
  AGENT_NAME: Mediator
  WALLET_NAME: mediator
  WALLET_KEY: ${WALLET_KEY}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_ADMIN_USER: ${POSTGRES_ADMIN_USER}
  POSTGRES_ADMIN_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
  AGENT_ENDPOINTS: "https://my-mediator.com,wss://my-mediator.com"
  LOG_LEVEL: 2


## Service Values
service_name: mediator


## Ingress Values
ingress_name: mediator_ingress
cluster_issuer_name: CLUSTER_ISSUER-NAME
host_name: HOST_NAME
certificate_secret_name: CERTIFICATE_SECRET_NAME